a= str(99)
b= int(99)
c= float(99)
d= bool(99)
e= complex(99)
f= list('keshav')
g= tuple('keshav')
#h= set(99)
#i= dict(99)
#j= frozenset(99)
k= bytes(2)
l= bytearray(3)
#m= memoryview(99)
n= None
print(a,"  ",b,"  ",c,"  ",d,"  ",e,"  ",f,"  ",g,"  ",k,"  ",l,"  ",n)